[2023-02-10 14:23:22,408] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [queued]>
[2023-02-10 14:23:22,410] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [queued]>
[2023-02-10 14:23:22,410] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:23:22,410] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 14:23:22,410] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:23:22,413] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-12-26 00:00:00+00:00
[2023-02-10 14:23:22,415] {standard_task_runner.py:52} INFO - Started process 33784 to run task
[2023-02-10 14:23:22,417] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-12-26T00:00:00+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmp854shy8h', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpo859eiop']
[2023-02-10 14:23:22,418] {standard_task_runner.py:80} INFO - Job 68: Subtask cria_pasta
[2023-02-10 14:23:22,444] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 14:23:22,455] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line -1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2023-02-10 14:23:22,458] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221226T000000, start_date=20230210T142322, end_date=20230210T142322
[2023-02-10 14:23:22,461] {standard_task_runner.py:92} ERROR - Failed to execute job 68 for task cria_pasta (unexpected end of template, expected ','.; 33784)
[2023-02-10 14:23:22,477] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-10 14:23:22,487] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-10 14:28:38,015] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [queued]>
[2023-02-10 14:28:38,018] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [queued]>
[2023-02-10 14:28:38,018] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:28:38,018] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 14:28:38,018] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:28:38,022] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-12-26 00:00:00+00:00
[2023-02-10 14:28:38,024] {standard_task_runner.py:52} INFO - Started process 34544 to run task
[2023-02-10 14:28:38,026] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-12-26T00:00:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpf5w3qyxm', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmp6xkckcei']
[2023-02-10 14:28:38,027] {standard_task_runner.py:80} INFO - Job 52: Subtask cria_pasta
[2023-02-10 14:28:38,045] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 14:28:38,062] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-12-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-26T00:00:00+00:00
[2023-02-10 14:28:38,063] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T
[2023-02-10 14:28:38,063] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p  "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/semana=2023-01-02T00:00:00+00:00" ']
[2023-02-10 14:28:38,067] {subprocess.py:85} INFO - Output:
[2023-02-10 14:28:38,076] {subprocess.py:96} INFO - Command exited with return code 0
[2023-02-10 14:28:38,084] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221226T000000, start_date=20230210T142838, end_date=20230210T142838
[2023-02-10 14:28:38,088] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-10 14:28:38,097] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-02-10 14:31:38,764] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [queued]>
[2023-02-10 14:31:38,767] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [queued]>
[2023-02-10 14:31:38,767] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:31:38,768] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 14:31:38,768] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:31:38,771] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-12-26 00:00:00+00:00
[2023-02-10 14:31:38,773] {standard_task_runner.py:52} INFO - Started process 35061 to run task
[2023-02-10 14:31:38,776] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-12-26T00:00:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpooa308c1', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpwzq5p59j']
[2023-02-10 14:31:38,777] {standard_task_runner.py:80} INFO - Job 54: Subtask cria_pasta
[2023-02-10 14:31:38,802] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 14:31:38,812] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line -1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2023-02-10 14:31:38,817] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221226T000000, start_date=20230210T143138, end_date=20230210T143138
[2023-02-10 14:31:38,819] {standard_task_runner.py:92} ERROR - Failed to execute job 54 for task cria_pasta (unexpected end of template, expected ','.; 35061)
[2023-02-10 14:31:38,835] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-10 14:31:38,845] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-10 14:46:20,516] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [queued]>
[2023-02-10 14:46:20,519] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [queued]>
[2023-02-10 14:46:20,519] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:46:20,519] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 14:46:20,519] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:46:20,522] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-12-26 00:00:00+00:00
[2023-02-10 14:46:20,524] {standard_task_runner.py:52} INFO - Started process 36829 to run task
[2023-02-10 14:46:20,527] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-12-26T00:00:00+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpwztt0uj7', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpiiko2xey']
[2023-02-10 14:46:20,528] {standard_task_runner.py:80} INFO - Job 56: Subtask cria_pasta
[2023-02-10 14:46:20,548] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 14:46:20,558] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/sandbox.py", line 407, in getattr
    value = getattr(obj, attribute)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/runtime.py", line 753, in __getattr__
    return self._fail_with_undefined_error()
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/runtime.py", line 747, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'pendulum.datetime.DateTime object' has no attribute 'pendulum'
[2023-02-10 14:46:20,562] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221226T000000, start_date=20230210T144620, end_date=20230210T144620
[2023-02-10 14:46:20,565] {standard_task_runner.py:92} ERROR - Failed to execute job 56 for task cria_pasta ('pendulum.datetime.DateTime object' has no attribute 'pendulum'; 36829)
[2023-02-10 14:46:20,588] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-10 14:46:20,595] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-10 14:48:38,547] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [queued]>
[2023-02-10 14:48:38,550] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [queued]>
[2023-02-10 14:48:38,550] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:48:38,550] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 14:48:38,550] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:48:38,554] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-12-26 00:00:00+00:00
[2023-02-10 14:48:38,556] {standard_task_runner.py:52} INFO - Started process 37217 to run task
[2023-02-10 14:48:38,559] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-12-26T00:00:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpukaubm39', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpjqr6r8_b']
[2023-02-10 14:48:38,559] {standard_task_runner.py:80} INFO - Job 58: Subtask cria_pasta
[2023-02-10 14:48:38,577] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 14:48:38,587] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line -1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2023-02-10 14:48:38,592] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221226T000000, start_date=20230210T144838, end_date=20230210T144838
[2023-02-10 14:48:38,595] {standard_task_runner.py:92} ERROR - Failed to execute job 58 for task cria_pasta (unexpected end of template, expected ','.; 37217)
[2023-02-10 14:48:38,618] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-10 14:48:38,626] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-10 14:52:59,237] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [queued]>
[2023-02-10 14:52:59,239] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [queued]>
[2023-02-10 14:52:59,239] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:52:59,239] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 14:52:59,239] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:52:59,242] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-12-26 00:00:00+00:00
[2023-02-10 14:52:59,244] {standard_task_runner.py:52} INFO - Started process 37867 to run task
[2023-02-10 14:52:59,247] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-12-26T00:00:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpeh269uva', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpewwttdri']
[2023-02-10 14:52:59,248] {standard_task_runner.py:80} INFO - Job 60: Subtask cria_pasta
[2023-02-10 14:52:59,265] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 14:52:59,280] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-12-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-26T00:00:00+00:00
[2023-02-10 14:52:59,281] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T
[2023-02-10 14:52:59,281] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p  "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/semana=2023-01-02T00:00:00+00:00"']
[2023-02-10 14:52:59,285] {subprocess.py:85} INFO - Output:
[2023-02-10 14:52:59,289] {subprocess.py:96} INFO - Command exited with return code 0
[2023-02-10 14:52:59,297] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221226T000000, start_date=20230210T145259, end_date=20230210T145259
[2023-02-10 14:52:59,308] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-10 14:52:59,314] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-10 14:54:28,135] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [queued]>
[2023-02-10 14:54:28,137] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [queued]>
[2023-02-10 14:54:28,137] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:54:28,137] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 14:54:28,137] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:54:28,141] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-12-26 00:00:00+00:00
[2023-02-10 14:54:28,143] {standard_task_runner.py:52} INFO - Started process 38157 to run task
[2023-02-10 14:54:28,146] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-12-26T00:00:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpnzwa5ih3', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmp8wv8ximk']
[2023-02-10 14:54:28,147] {standard_task_runner.py:80} INFO - Job 62: Subtask cria_pasta
[2023-02-10 14:54:28,177] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 14:54:28,194] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-12-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-26T00:00:00+00:00
[2023-02-10 14:54:28,195] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T
[2023-02-10 14:54:28,195] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p  "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/semana=2023-01-02T00:00:00+00:00"']
[2023-02-10 14:54:28,199] {subprocess.py:85} INFO - Output:
[2023-02-10 14:54:28,204] {subprocess.py:96} INFO - Command exited with return code 0
[2023-02-10 14:54:28,213] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221226T000000, start_date=20230210T145428, end_date=20230210T145428
[2023-02-10 14:54:28,248] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-10 14:54:28,258] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-02-10 14:58:43,990] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [queued]>
[2023-02-10 14:58:43,992] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [queued]>
[2023-02-10 14:58:43,992] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:58:43,993] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 14:58:43,993] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:58:43,996] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-12-26 00:00:00+00:00
[2023-02-10 14:58:43,998] {standard_task_runner.py:52} INFO - Started process 38859 to run task
[2023-02-10 14:58:44,001] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-12-26T00:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpq_58h3af', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmphf_i9x3x']
[2023-02-10 14:58:44,002] {standard_task_runner.py:80} INFO - Job 64: Subtask cria_pasta
[2023-02-10 14:58:44,022] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 14:58:44,039] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-12-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-26T00:00:00+00:00
[2023-02-10 14:58:44,039] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T
[2023-02-10 14:58:44,040] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p  "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/semana=2023-01-02T00:00:00+00:00"']
[2023-02-10 14:58:44,043] {subprocess.py:85} INFO - Output:
[2023-02-10 14:58:44,048] {subprocess.py:96} INFO - Command exited with return code 0
[2023-02-10 14:58:44,055] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221226T000000, start_date=20230210T145843, end_date=20230210T145844
[2023-02-10 14:58:44,062] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-10 14:58:44,070] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-02-10 17:29:15,782] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [queued]>
[2023-02-10 17:29:15,784] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [queued]>
[2023-02-10 17:29:15,784] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 17:29:15,784] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 17:29:15,784] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 17:29:15,788] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-12-26 00:00:00+00:00
[2023-02-10 17:29:15,790] {standard_task_runner.py:52} INFO - Started process 55328 to run task
[2023-02-10 17:29:15,793] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-12-26T00:00:00+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpvjlq1rwh', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmp8e0ill8m']
[2023-02-10 17:29:15,794] {standard_task_runner.py:80} INFO - Job 102: Subtask cria_pasta
[2023-02-10 17:29:15,810] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 17:29:15,827] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-12-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-26T00:00:00+00:00
[2023-02-10 17:29:15,827] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T
[2023-02-10 17:29:15,828] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p  "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/semana=2023-01-02"']
[2023-02-10 17:29:15,831] {subprocess.py:85} INFO - Output:
[2023-02-10 17:29:15,835] {subprocess.py:96} INFO - Command exited with return code 0
[2023-02-10 17:29:15,843] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221226T000000, start_date=20230210T172915, end_date=20230210T172915
[2023-02-10 17:29:15,855] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-10 17:29:15,864] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-02-10 17:33:16,750] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [queued]>
[2023-02-10 17:33:16,752] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [queued]>
[2023-02-10 17:33:16,752] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 17:33:16,752] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 17:33:16,752] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 17:33:16,756] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-12-26 00:00:00+00:00
[2023-02-10 17:33:16,758] {standard_task_runner.py:52} INFO - Started process 55902 to run task
[2023-02-10 17:33:16,760] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-12-26T00:00:00+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmp08m99h0x', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpwzj0buq8']
[2023-02-10 17:33:16,761] {standard_task_runner.py:80} INFO - Job 118: Subtask cria_pasta
[2023-02-10 17:33:16,785] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 17:33:16,802] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-12-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-26T00:00:00+00:00
[2023-02-10 17:33:16,803] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T
[2023-02-10 17:33:16,803] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p  "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/semana=2023-01-02"']
[2023-02-10 17:33:16,807] {subprocess.py:85} INFO - Output:
[2023-02-10 17:33:16,813] {subprocess.py:96} INFO - Command exited with return code 0
[2023-02-10 17:33:16,820] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221226T000000, start_date=20230210T173316, end_date=20230210T173316
[2023-02-10 17:33:16,867] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-10 17:33:16,876] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
