[2023-02-10 14:23:25,358] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-02-10 14:23:25,359] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-02-10 14:23:25,359] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:23:25,359] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 14:23:25,360] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:23:25,363] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-01-02 00:00:00+00:00
[2023-02-10 14:23:25,365] {standard_task_runner.py:52} INFO - Started process 33793 to run task
[2023-02-10 14:23:25,368] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpwb2kccie', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmp53rdi9gf']
[2023-02-10 14:23:25,369] {standard_task_runner.py:80} INFO - Job 69: Subtask cria_pasta
[2023-02-10 14:23:25,391] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 14:23:25,402] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line -1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2023-02-10 14:23:25,404] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230102T000000, start_date=20230210T142325, end_date=20230210T142325
[2023-02-10 14:23:25,407] {standard_task_runner.py:92} ERROR - Failed to execute job 69 for task cria_pasta (unexpected end of template, expected ','.; 33793)
[2023-02-10 14:23:25,429] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-10 14:23:25,440] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-10 14:28:39,545] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-02-10 14:28:39,547] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-02-10 14:28:39,547] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:28:39,547] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 14:28:39,547] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:28:39,552] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-01-02 00:00:00+00:00
[2023-02-10 14:28:39,553] {standard_task_runner.py:52} INFO - Started process 34551 to run task
[2023-02-10 14:28:39,556] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmp4jt_jhy7', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpmglhw4bx']
[2023-02-10 14:28:39,557] {standard_task_runner.py:80} INFO - Job 53: Subtask cria_pasta
[2023-02-10 14:28:39,584] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 14:28:39,601] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-02T00:00:00+00:00
[2023-02-10 14:28:39,601] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T
[2023-02-10 14:28:39,602] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p  "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/semana=2023-01-09T00:00:00+00:00" ']
[2023-02-10 14:28:39,606] {subprocess.py:85} INFO - Output:
[2023-02-10 14:28:39,609] {subprocess.py:96} INFO - Command exited with return code 0
[2023-02-10 14:28:39,617] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230102T000000, start_date=20230210T142839, end_date=20230210T142839
[2023-02-10 14:28:39,663] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-10 14:28:39,674] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-02-10 14:31:40,520] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-02-10 14:31:40,522] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-02-10 14:31:40,522] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:31:40,522] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 14:31:40,522] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:31:40,525] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-01-02 00:00:00+00:00
[2023-02-10 14:31:40,527] {standard_task_runner.py:52} INFO - Started process 35066 to run task
[2023-02-10 14:31:40,530] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpmwvo9ucw', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpfm2n7t91']
[2023-02-10 14:31:40,530] {standard_task_runner.py:80} INFO - Job 55: Subtask cria_pasta
[2023-02-10 14:31:40,545] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 14:31:40,554] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line -1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2023-02-10 14:31:40,556] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230102T000000, start_date=20230210T143140, end_date=20230210T143140
[2023-02-10 14:31:40,559] {standard_task_runner.py:92} ERROR - Failed to execute job 55 for task cria_pasta (unexpected end of template, expected ','.; 35066)
[2023-02-10 14:31:40,590] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-10 14:31:40,600] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-10 14:46:22,313] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-02-10 14:46:22,315] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-02-10 14:46:22,316] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:46:22,316] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 14:46:22,316] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:46:22,319] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-01-02 00:00:00+00:00
[2023-02-10 14:46:22,321] {standard_task_runner.py:52} INFO - Started process 36839 to run task
[2023-02-10 14:46:22,323] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpc2za20y1', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpx8yl60bq']
[2023-02-10 14:46:22,324] {standard_task_runner.py:80} INFO - Job 57: Subtask cria_pasta
[2023-02-10 14:46:22,341] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 14:46:22,350] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/sandbox.py", line 407, in getattr
    value = getattr(obj, attribute)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/runtime.py", line 753, in __getattr__
    return self._fail_with_undefined_error()
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/runtime.py", line 747, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'pendulum.datetime.DateTime object' has no attribute 'pendulum'
[2023-02-10 14:46:22,353] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230102T000000, start_date=20230210T144622, end_date=20230210T144622
[2023-02-10 14:46:22,355] {standard_task_runner.py:92} ERROR - Failed to execute job 57 for task cria_pasta ('pendulum.datetime.DateTime object' has no attribute 'pendulum'; 36839)
[2023-02-10 14:46:22,385] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-10 14:46:22,393] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-10 14:48:40,006] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-02-10 14:48:40,008] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-02-10 14:48:40,008] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:48:40,008] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 14:48:40,008] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:48:40,013] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-01-02 00:00:00+00:00
[2023-02-10 14:48:40,015] {standard_task_runner.py:52} INFO - Started process 37221 to run task
[2023-02-10 14:48:40,017] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpyvffbmr3', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpcoifqhoy']
[2023-02-10 14:48:40,018] {standard_task_runner.py:80} INFO - Job 59: Subtask cria_pasta
[2023-02-10 14:48:40,034] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 14:48:40,043] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line -1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2023-02-10 14:48:40,045] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230102T000000, start_date=20230210T144840, end_date=20230210T144840
[2023-02-10 14:48:40,048] {standard_task_runner.py:92} ERROR - Failed to execute job 59 for task cria_pasta (unexpected end of template, expected ','.; 37221)
[2023-02-10 14:48:40,077] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-10 14:48:40,085] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-10 14:53:00,694] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-02-10 14:53:00,697] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-02-10 14:53:00,697] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:53:00,697] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 14:53:00,697] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:53:00,701] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-01-02 00:00:00+00:00
[2023-02-10 14:53:00,702] {standard_task_runner.py:52} INFO - Started process 37874 to run task
[2023-02-10 14:53:00,705] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpurzk0qu2', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmp5r_d69p_']
[2023-02-10 14:53:00,706] {standard_task_runner.py:80} INFO - Job 61: Subtask cria_pasta
[2023-02-10 14:53:00,724] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 14:53:00,741] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-02T00:00:00+00:00
[2023-02-10 14:53:00,742] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T
[2023-02-10 14:53:00,742] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p  "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/semana=2023-01-09T00:00:00+00:00"']
[2023-02-10 14:53:00,746] {subprocess.py:85} INFO - Output:
[2023-02-10 14:53:00,749] {subprocess.py:96} INFO - Command exited with return code 0
[2023-02-10 14:53:00,758] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230102T000000, start_date=20230210T145300, end_date=20230210T145300
[2023-02-10 14:53:00,766] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-10 14:53:00,773] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-10 14:54:29,972] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-02-10 14:54:29,975] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-02-10 14:54:29,975] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:54:29,975] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 14:54:29,975] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:54:29,979] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-01-02 00:00:00+00:00
[2023-02-10 14:54:29,980] {standard_task_runner.py:52} INFO - Started process 38162 to run task
[2023-02-10 14:54:29,983] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpphvxgoa2', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmptvug62p0']
[2023-02-10 14:54:29,984] {standard_task_runner.py:80} INFO - Job 63: Subtask cria_pasta
[2023-02-10 14:54:29,999] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 14:54:30,014] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-02T00:00:00+00:00
[2023-02-10 14:54:30,015] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T
[2023-02-10 14:54:30,015] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p  "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/semana=2023-01-09T00:00:00+00:00"']
[2023-02-10 14:54:30,019] {subprocess.py:85} INFO - Output:
[2023-02-10 14:54:30,022] {subprocess.py:96} INFO - Command exited with return code 0
[2023-02-10 14:54:30,030] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230102T000000, start_date=20230210T145429, end_date=20230210T145430
[2023-02-10 14:54:30,045] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-10 14:54:30,053] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-02-10 14:58:45,423] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-02-10 14:58:45,426] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-02-10 14:58:45,426] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:58:45,426] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 14:58:45,426] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:58:45,429] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-01-02 00:00:00+00:00
[2023-02-10 14:58:45,431] {standard_task_runner.py:52} INFO - Started process 38864 to run task
[2023-02-10 14:58:45,433] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmp01pcuutz', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmp4qrdwxyu']
[2023-02-10 14:58:45,434] {standard_task_runner.py:80} INFO - Job 65: Subtask cria_pasta
[2023-02-10 14:58:45,450] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 14:58:45,472] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-02T00:00:00+00:00
[2023-02-10 14:58:45,473] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T
[2023-02-10 14:58:45,473] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p  "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/semana=2023-01-09T00:00:00+00:00"']
[2023-02-10 14:58:45,477] {subprocess.py:85} INFO - Output:
[2023-02-10 14:58:45,480] {subprocess.py:96} INFO - Command exited with return code 0
[2023-02-10 14:58:45,487] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230102T000000, start_date=20230210T145845, end_date=20230210T145845
[2023-02-10 14:58:45,495] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-10 14:58:45,504] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-02-10 17:29:17,634] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-02-10 17:29:17,637] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-02-10 17:29:17,637] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 17:29:17,637] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 17:29:17,637] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 17:29:17,641] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-01-02 00:00:00+00:00
[2023-02-10 17:29:17,643] {standard_task_runner.py:52} INFO - Started process 55335 to run task
[2023-02-10 17:29:17,645] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpj8y3vklu', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpsit_k9lj']
[2023-02-10 17:29:17,646] {standard_task_runner.py:80} INFO - Job 103: Subtask cria_pasta
[2023-02-10 17:29:17,662] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 17:29:17,679] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-02T00:00:00+00:00
[2023-02-10 17:29:17,679] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T
[2023-02-10 17:29:17,680] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p  "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/semana=2023-01-09"']
[2023-02-10 17:29:17,684] {subprocess.py:85} INFO - Output:
[2023-02-10 17:29:17,690] {subprocess.py:96} INFO - Command exited with return code 0
[2023-02-10 17:29:17,698] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230102T000000, start_date=20230210T172917, end_date=20230210T172917
[2023-02-10 17:29:17,707] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-10 17:29:17,716] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-02-10 17:33:18,214] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-02-10 17:33:18,216] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-02-10 17:33:18,217] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 17:33:18,217] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 17:33:18,217] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 17:33:18,221] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-01-02 00:00:00+00:00
[2023-02-10 17:33:18,222] {standard_task_runner.py:52} INFO - Started process 55907 to run task
[2023-02-10 17:33:18,225] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpxo167mtb', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpb333l7d9']
[2023-02-10 17:33:18,226] {standard_task_runner.py:80} INFO - Job 119: Subtask cria_pasta
[2023-02-10 17:33:18,251] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-02T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 17:33:18,268] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-02T00:00:00+00:00
[2023-02-10 17:33:18,269] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T
[2023-02-10 17:33:18,269] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p  "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/semana=2023-01-09"']
[2023-02-10 17:33:18,273] {subprocess.py:85} INFO - Output:
[2023-02-10 17:33:18,276] {subprocess.py:96} INFO - Command exited with return code 0
[2023-02-10 17:33:18,283] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230102T000000, start_date=20230210T173318, end_date=20230210T173318
[2023-02-10 17:33:18,326] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-10 17:33:18,335] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
