[2023-02-10 17:28:52,299] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-31T00:00:00+00:00 [queued]>
[2023-02-10 17:28:52,301] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-31T00:00:00+00:00 [queued]>
[2023-02-10 17:28:52,301] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 17:28:52,301] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 17:28:52,301] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 17:28:52,305] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-10-31 00:00:00+00:00
[2023-02-10 17:28:52,307] {standard_task_runner.py:52} INFO - Started process 55251 to run task
[2023-02-10 17:28:52,309] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-10-31T00:00:00+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmp5ghbazo8', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpq430e7ws']
[2023-02-10 17:28:52,310] {standard_task_runner.py:80} INFO - Job 88: Subtask extrai_dados
[2023-02-10 17:28:52,325] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-31T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 17:28:52,344] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-10-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-31T00:00:00+00:00
[2023-02-10 17:28:52,457] {local_task_job.py:156} INFO - Task exited with return code Negsignal.SIGSEGV
[2023-02-10 17:28:52,463] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20221031T000000, start_date=20230210T172852, end_date=20230210T172852
[2023-02-10 17:28:52,469] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
