[2023-02-10 14:23:31,928] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2023-02-10 14:23:31,930] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2023-02-10 14:23:31,930] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:23:31,930] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 14:23:31,930] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:23:31,934] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-01-23 00:00:00+00:00
[2023-02-10 14:23:31,936] {standard_task_runner.py:52} INFO - Started process 33811 to run task
[2023-02-10 14:23:31,938] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-01-23T00:00:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpkhwtyjrw', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmphlkkp1wr']
[2023-02-10 14:23:31,939] {standard_task_runner.py:80} INFO - Job 72: Subtask cria_pasta
[2023-02-10 14:23:31,957] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 14:23:31,967] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line -1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2023-02-10 14:23:31,970] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230123T000000, start_date=20230210T142331, end_date=20230210T142331
[2023-02-10 14:23:31,972] {standard_task_runner.py:92} ERROR - Failed to execute job 72 for task cria_pasta (unexpected end of template, expected ','.; 33811)
[2023-02-10 14:23:32,001] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-10 14:23:32,012] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-10 14:28:48,643] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2023-02-10 14:28:48,645] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2023-02-10 14:28:48,645] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:28:48,645] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 14:28:48,645] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:28:48,649] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-01-23 00:00:00+00:00
[2023-02-10 14:28:48,650] {standard_task_runner.py:52} INFO - Started process 34593 to run task
[2023-02-10 14:28:48,653] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-01-23T00:00:00+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmp9_xta2ly', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpy_dwqszp']
[2023-02-10 14:28:48,653] {standard_task_runner.py:80} INFO - Job 59: Subtask cria_pasta
[2023-02-10 14:28:48,672] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 14:28:48,689] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2023-01-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-23T00:00:00+00:00
[2023-02-10 14:28:48,690] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T
[2023-02-10 14:28:48,690] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p  "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/semana=2023-01-30T00:00:00+00:00" ']
[2023-02-10 14:28:48,693] {subprocess.py:85} INFO - Output:
[2023-02-10 14:28:48,696] {subprocess.py:96} INFO - Command exited with return code 0
[2023-02-10 14:28:48,704] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230123T000000, start_date=20230210T142848, end_date=20230210T142848
[2023-02-10 14:28:48,713] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-10 14:28:48,722] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-02-10 14:31:48,690] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2023-02-10 14:31:48,692] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2023-02-10 14:31:48,692] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:31:48,692] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 14:31:48,692] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:31:48,696] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-01-23 00:00:00+00:00
[2023-02-10 14:31:48,698] {standard_task_runner.py:52} INFO - Started process 35088 to run task
[2023-02-10 14:31:48,700] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-01-23T00:00:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpv9ur4n9r', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpzusrz7t2']
[2023-02-10 14:31:48,701] {standard_task_runner.py:80} INFO - Job 58: Subtask cria_pasta
[2023-02-10 14:31:48,717] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 14:31:48,735] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line -1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2023-02-10 14:31:48,737] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230123T000000, start_date=20230210T143148, end_date=20230210T143148
[2023-02-10 14:31:48,740] {standard_task_runner.py:92} ERROR - Failed to execute job 58 for task cria_pasta (unexpected end of template, expected ','.; 35088)
[2023-02-10 14:31:48,763] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-10 14:31:48,773] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-10 14:46:30,304] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2023-02-10 14:46:30,307] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2023-02-10 14:46:30,307] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:46:30,307] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 14:46:30,307] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:46:30,311] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-01-23 00:00:00+00:00
[2023-02-10 14:46:30,314] {standard_task_runner.py:52} INFO - Started process 36862 to run task
[2023-02-10 14:46:30,316] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-01-23T00:00:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpou1zfkg2', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmp80x6hlk5']
[2023-02-10 14:46:30,317] {standard_task_runner.py:80} INFO - Job 60: Subtask cria_pasta
[2023-02-10 14:46:30,338] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 14:46:30,354] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/sandbox.py", line 407, in getattr
    value = getattr(obj, attribute)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/runtime.py", line 753, in __getattr__
    return self._fail_with_undefined_error()
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/runtime.py", line 747, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'pendulum.datetime.DateTime object' has no attribute 'pendulum'
[2023-02-10 14:46:30,358] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230123T000000, start_date=20230210T144630, end_date=20230210T144630
[2023-02-10 14:46:30,361] {standard_task_runner.py:92} ERROR - Failed to execute job 60 for task cria_pasta ('pendulum.datetime.DateTime object' has no attribute 'pendulum'; 36862)
[2023-02-10 14:46:30,377] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-10 14:46:30,386] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-10 14:48:47,299] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2023-02-10 14:48:47,301] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2023-02-10 14:48:47,301] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:48:47,301] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 14:48:47,301] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:48:47,304] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-01-23 00:00:00+00:00
[2023-02-10 14:48:47,307] {standard_task_runner.py:52} INFO - Started process 37244 to run task
[2023-02-10 14:48:47,310] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-01-23T00:00:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpc46yyaux', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpic9g86iw']
[2023-02-10 14:48:47,311] {standard_task_runner.py:80} INFO - Job 62: Subtask cria_pasta
[2023-02-10 14:48:47,342] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 14:48:47,352] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/venv/lib/python3.10/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line -1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2023-02-10 14:48:47,354] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230123T000000, start_date=20230210T144847, end_date=20230210T144847
[2023-02-10 14:48:47,357] {standard_task_runner.py:92} ERROR - Failed to execute job 62 for task cria_pasta (unexpected end of template, expected ','.; 37244)
[2023-02-10 14:48:47,368] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-10 14:48:47,375] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-10 14:53:07,713] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2023-02-10 14:53:07,715] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2023-02-10 14:53:07,715] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:53:07,715] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 14:53:07,715] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:53:07,719] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-01-23 00:00:00+00:00
[2023-02-10 14:53:07,721] {standard_task_runner.py:52} INFO - Started process 37943 to run task
[2023-02-10 14:53:07,724] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-01-23T00:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpacwnzera', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmp9p3vtsvd']
[2023-02-10 14:53:07,725] {standard_task_runner.py:80} INFO - Job 64: Subtask cria_pasta
[2023-02-10 14:53:07,744] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 14:53:07,766] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2023-01-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-23T00:00:00+00:00
[2023-02-10 14:53:07,767] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T
[2023-02-10 14:53:07,767] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p  "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/semana=2023-01-30T00:00:00+00:00"']
[2023-02-10 14:53:07,771] {subprocess.py:85} INFO - Output:
[2023-02-10 14:53:07,774] {subprocess.py:96} INFO - Command exited with return code 0
[2023-02-10 14:53:07,782] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230123T000000, start_date=20230210T145307, end_date=20230210T145307
[2023-02-10 14:53:07,829] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-10 14:53:07,837] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-02-10 14:54:39,959] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2023-02-10 14:54:39,962] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2023-02-10 14:54:39,962] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:54:39,962] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 14:54:39,962] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:54:39,966] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-01-23 00:00:00+00:00
[2023-02-10 14:54:39,968] {standard_task_runner.py:52} INFO - Started process 38266 to run task
[2023-02-10 14:54:39,971] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-01-23T00:00:00+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpaat72qlp', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmprehz_mdy']
[2023-02-10 14:54:39,972] {standard_task_runner.py:80} INFO - Job 69: Subtask cria_pasta
[2023-02-10 14:54:39,992] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 14:54:40,009] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2023-01-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-23T00:00:00+00:00
[2023-02-10 14:54:40,010] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T
[2023-02-10 14:54:40,010] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p  "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/semana=2023-01-30T00:00:00+00:00"']
[2023-02-10 14:54:40,014] {subprocess.py:85} INFO - Output:
[2023-02-10 14:54:40,017] {subprocess.py:96} INFO - Command exited with return code 0
[2023-02-10 14:54:40,025] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230123T000000, start_date=20230210T145439, end_date=20230210T145440
[2023-02-10 14:54:40,033] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-10 14:54:40,042] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-02-10 14:58:55,115] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2023-02-10 14:58:55,118] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2023-02-10 14:58:55,118] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:58:55,118] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 14:58:55,118] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 14:58:55,122] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-01-23 00:00:00+00:00
[2023-02-10 14:58:55,124] {standard_task_runner.py:52} INFO - Started process 38898 to run task
[2023-02-10 14:58:55,126] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-01-23T00:00:00+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmp8nmws5zj', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmphqkw64ql']
[2023-02-10 14:58:55,127] {standard_task_runner.py:80} INFO - Job 71: Subtask cria_pasta
[2023-02-10 14:58:55,150] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 14:58:55,168] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2023-01-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-23T00:00:00+00:00
[2023-02-10 14:58:55,168] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T
[2023-02-10 14:58:55,169] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p  "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/semana=2023-01-30T00:00:00+00:00"']
[2023-02-10 14:58:55,173] {subprocess.py:85} INFO - Output:
[2023-02-10 14:58:55,177] {subprocess.py:96} INFO - Command exited with return code 0
[2023-02-10 14:58:55,185] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230123T000000, start_date=20230210T145855, end_date=20230210T145855
[2023-02-10 14:58:55,228] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-10 14:58:55,238] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-02-10 17:29:27,376] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2023-02-10 17:29:27,378] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2023-02-10 17:29:27,378] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 17:29:27,378] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 17:29:27,378] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 17:29:27,382] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-01-23 00:00:00+00:00
[2023-02-10 17:29:27,384] {standard_task_runner.py:52} INFO - Started process 55369 to run task
[2023-02-10 17:29:27,386] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-01-23T00:00:00+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmphxl490o2', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpv8bcva0m']
[2023-02-10 17:29:27,387] {standard_task_runner.py:80} INFO - Job 109: Subtask cria_pasta
[2023-02-10 17:29:27,410] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 17:29:27,430] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2023-01-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-23T00:00:00+00:00
[2023-02-10 17:29:27,430] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T
[2023-02-10 17:29:27,431] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p  "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/semana=2023-01-30"']
[2023-02-10 17:29:27,434] {subprocess.py:85} INFO - Output:
[2023-02-10 17:29:27,437] {subprocess.py:96} INFO - Command exited with return code 0
[2023-02-10 17:29:27,445] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230123T000000, start_date=20230210T172927, end_date=20230210T172927
[2023-02-10 17:29:27,491] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-10 17:29:27,502] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-02-10 17:33:28,838] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2023-02-10 17:33:28,840] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2023-02-10 17:33:28,840] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 17:33:28,840] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 17:33:28,840] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 17:33:28,843] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-01-23 00:00:00+00:00
[2023-02-10 17:33:28,845] {standard_task_runner.py:52} INFO - Started process 55942 to run task
[2023-02-10 17:33:28,848] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-01-23T00:00:00+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmp9s60khwz', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpi7q9hksy']
[2023-02-10 17:33:28,848] {standard_task_runner.py:80} INFO - Job 125: Subtask cria_pasta
[2023-02-10 17:33:28,877] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 17:33:28,894] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2023-01-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-23T00:00:00+00:00
[2023-02-10 17:33:28,895] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T
[2023-02-10 17:33:28,895] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p  "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/semana=2023-01-30"']
[2023-02-10 17:33:28,899] {subprocess.py:85} INFO - Output:
[2023-02-10 17:33:28,902] {subprocess.py:96} INFO - Command exited with return code 0
[2023-02-10 17:33:28,910] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230123T000000, start_date=20230210T173328, end_date=20230210T173328
[2023-02-10 17:33:28,947] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-10 17:33:28,958] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-02-10 17:35:51,874] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2023-02-10 17:35:51,877] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2023-02-10 17:35:51,877] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 17:35:51,877] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 17:35:51,877] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 17:35:51,881] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-01-23 00:00:00+00:00
[2023-02-10 17:35:51,884] {standard_task_runner.py:52} INFO - Started process 56270 to run task
[2023-02-10 17:35:51,888] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-01-23T00:00:00+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmplbnhim1n', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpxhgsm5j6']
[2023-02-10 17:35:51,890] {standard_task_runner.py:80} INFO - Job 120: Subtask cria_pasta
[2023-02-10 17:35:51,910] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 17:35:51,928] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2023-01-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-23T00:00:00+00:00
[2023-02-10 17:35:51,929] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T
[2023-02-10 17:35:51,929] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p  "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/semana=2023-01-30"']
[2023-02-10 17:35:51,933] {subprocess.py:85} INFO - Output:
[2023-02-10 17:35:51,938] {subprocess.py:96} INFO - Command exited with return code 0
[2023-02-10 17:35:51,946] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230123T000000, start_date=20230210T173551, end_date=20230210T173551
[2023-02-10 17:35:51,992] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-10 17:35:52,003] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-02-10 17:46:49,126] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2023-02-10 17:46:49,128] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2023-02-10 17:46:49,128] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 17:46:49,128] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 17:46:49,128] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 17:46:49,132] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-01-23 00:00:00+00:00
[2023-02-10 17:46:49,134] {standard_task_runner.py:52} INFO - Started process 57680 to run task
[2023-02-10 17:46:49,136] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-01-23T00:00:00+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmppkqpj2as', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmprxuh8tqy']
[2023-02-10 17:46:49,137] {standard_task_runner.py:80} INFO - Job 122: Subtask cria_pasta
[2023-02-10 17:46:49,159] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 17:46:49,176] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2023-01-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-23T00:00:00+00:00
[2023-02-10 17:46:49,177] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T
[2023-02-10 17:46:49,177] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p  "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/semana=2023-01-30"']
[2023-02-10 17:46:49,181] {subprocess.py:85} INFO - Output:
[2023-02-10 17:46:49,186] {subprocess.py:96} INFO - Command exited with return code 0
[2023-02-10 17:46:49,193] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230123T000000, start_date=20230210T174649, end_date=20230210T174649
[2023-02-10 17:46:49,198] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-10 17:46:49,207] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-02-10 17:56:10,415] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2023-02-10 17:56:10,417] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2023-02-10 17:56:10,417] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 17:56:10,417] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-10 17:56:10,417] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-10 17:56:10,421] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-01-23 00:00:00+00:00
[2023-02-10 17:56:10,423] {standard_task_runner.py:52} INFO - Started process 59042 to run task
[2023-02-10 17:56:10,425] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-01-23T00:00:00+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmph9au03mu', '--error-file', '/var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T/tmpjgelox_r']
[2023-02-10 17:56:10,426] {standard_task_runner.py:80} INFO - Job 124: Subtask cria_pasta
[2023-02-10 17:56:10,445] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-01-23T00:00:00+00:00 [running]> on host airdefrancilene.lan
[2023-02-10 17:56:10,463] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2023-01-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-23T00:00:00+00:00
[2023-02-10 17:56:10,464] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/b_/44w2czd50d77jsslrsmc4_sc0000gn/T
[2023-02-10 17:56:10,464] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p  "/Users/francilenesilva/Documents/data-engineer/apache-airflow/orquestrando-pipeline1/data-pipeline/airflow-alura/semana=2023-01-30"']
[2023-02-10 17:56:10,468] {subprocess.py:85} INFO - Output:
[2023-02-10 17:56:10,473] {subprocess.py:96} INFO - Command exited with return code 0
[2023-02-10 17:56:10,482] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230123T000000, start_date=20230210T175610, end_date=20230210T175610
[2023-02-10 17:56:10,487] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-10 17:56:10,496] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
